# `node-modules` to use a `node_modules` directory, `pnp` for plug-and-play
# Run `yarn dlx @yarnpkg/sdks vscode` if changing from node-modules to pnp so VS Code finds types
nodeLinker: pnp
plugins:
  - ./scripts/yarn/pluginScriptHandler.js
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
yarnPath: .yarn/releases/yarn-3.2.2.cjs