nodeLinker: node-modules

plugins:
  - ./scripts/yarn/pluginScriptHandler.js
  # Automatically adds @types/ packages into your dependencies
  # when you add a package that doesn't include its own types
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
    # Adds support for the new release workflow, included by default starting from Yarn 4
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
    # Enforce rules in a `yarn.config.js` file
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

yarnPath: .yarn/releases/yarn-3.6.2.cjs
