# 'pnp' | 'node-modules'
# netlify-lambda needs node_modules to bundle directories out of
nodeLinker: node-modules

plugins:
  - ./scripts/yarn/pluginScriptHandler.js
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
