/**
 * Loads any scripts generated outside of the client bundle Webpack build,
 * e.g. a service worker generated by the project build process or third-
 * party code that should be either loaded by or bundled into the client
 * script bundle.
 */
import type { ScriptInit } from '../@types/general'
import { promiseErrorHandler } from '../errors/handlers'

export const registerServiceWorker: ScriptInit = () => {
  navigator.serviceWorker.register('/service-worker.js').catch(promiseErrorHandler)
}