/**
 * Loads any scripts generated outside of the client bundle Webpack build,
 * e.g. a service worker generated by the project build process or third-
 * party code that should be either loaded by or bundled into the client
 * script bundle.
 */
import type { ScriptInit } from '../../@types/general'
import { promiseErrorHandler } from '../../errors/handlers'

export const registerServiceWorker: ScriptInit = () => {
  if (`serviceWorker` in navigator) {
    navigator.serviceWorker
      .register('/service-worker.js', {
        /**
         * Content that the service worker controls, slash is default and means
         * all content under the app's origin
         */
        scope: '/',
      })
      .catch(promiseErrorHandler)
  }
}