#!/usr/bin/env node
const yargs = require('yargs')
const execSync = require('child_process').execSync

const { version } = require('./package.json')

yargs.version(version)

yargs.command({
  command: 'run-cypress',
  describe: `Runs Cypress tests to completion using a headless browser on port ${
    process.env.CYPRESS_baseUrl || '21702'
  }`,
  handler(argv) {
    execSync(
      `npx cross-env CYPRESS_baseUrl=${process.env.CYPRESS_baseUrl} npx cypress run \
      --browser chrome \
      --reporter junit \
      --reporter-options 'mochaFile=results/cypress/result.xml'`
    )
  },
})

yargs.parse()
